version: 0.2
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file cloudformation.yaml --kms-key-id kms-key-id --s3-bucket bucket-name 
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - cloudformation.yaml
    - outputSamTemplate.yaml