version: 0.2
phases:
  install:
    commands:
      - npm install
      # - npm run installation
      - npm run build
      - npm run install-build
      - aws cloudformation package --template-file ./build/templates/main.yaml --s3-bucket cicd-testing-serverless --output-template-file outputSamTemplate.yaml
      - ls -al
  pre_build:
    commands:
      - ls -al
  build:
    commands:
      - ls -al
  post_build:
    commands:
      - ls -al
artifacts:
  type: zip
  files:
    - ./build/templates/main.yaml
    - outputSamTemplate.yaml
