AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TimeFunction
      Description: this is a desc
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TimeFunction
      Description: this is a desc
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: POST


