AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TimeFunction
      Description: this is a desc
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MyTimeApiStage:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
            RestApiId: !ref timeApiStage
        MyTimeApiProd:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: POST
            RestApiId: !ref timeApiProd
  timeApiStage:
    Type: AWS::Serverless::Api
    Properties:
      Name: timeApi
      StageName: Stage
      DefinitionBody: this is desc Stage
      Cors:
        AllowMethods: GET,POST,DELETE 
        AllowHeaders: X-Forwarded-For 
  timeApiProd:
    Type: AWS::Serverless::Api
    Properties:
      Name: timeApi
      StageName: Prod
      DefinitionBody: this is desc Prod
      Cors:
        AllowMethods: GET,POST,DELETE 
        AllowHeaders: X-Forwarded-For 

