AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TimeFunction
      Description: this is a desc
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MyTimeApiStage:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  timeApi:  
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: timeApi
      Description: this is a des for API
      FailOnWarnings: true
      ApiKeySourceType: AUTHORIZER
      Parameters:
        endpointConfigurationTypes: EDGE
  timeApiResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::GetAtt:
          - "timeApi"
          - "RootResourceId"
      PathPart: "dev"
      RestApiId:
        Ref: timeApi
  timeApitMethod:
  Type: "AWS::ApiGateway::Method"
  Properties:
    HttpMethod: "GET"
    AuthorizationType: "NONE"
    ResourceId:
      Ref: timeApiResource
    RestApiId:
      Ref: timeApi
    Integration:
      Type: "AWS"
      Uri:
        Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TimeFunction.Arn}/invocations"
      IntegrationHttpMethod: "GET"