AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  timeApi:  
    Fn::Transform:
      Name: 'AWS::Include'
      Parameters:
        Location : "s3://cicd-testing-serverless/partials/apiGateWay/restApi.yaml"
  TimeFunction:
    Fn::Transform:
      Name: 'AWS::Include'
      Parameters:
        Location : "s3://cicd-testing-serverless/partials/lambda/timer.yaml"
  timeApiResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId:
        Fn::GetAtt:
          - "timeApi"
          - "RootResourceId"
      PathPart: "dev"
      RestApiId:
        Ref: timeApi
  timeApitMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: "GET"
      AuthorizationType: "NONE"
      ResourceId:
        Ref: timeApiResource
      RestApiId:
        Ref: timeApi
      Integration:
        Type: "AWS"
        Uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TimeFunction.Arn}/invocations"
        IntegrationHttpMethod: "GET"
  timeApiDeploymentStage: 
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId:
          Ref: timeApi
        Description: Staging deployment of our Api
        StageName: Stage
    
    