AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  Fn::Transform:
    Name: 'AWS::Include'
    Parameters:
      Location : "s3://cicd-testing-serverless/partials/resources.yaml"